### ISSUE TITLE
Paste image, the file will be rename, but the name in .md is still the original one.

### ISSUE THREAD

**Issue by taso998** [reorx/obsidian-paste-image-rename#12] opened 2022-05-26 13:38 UTC
**Describe the bug**
Paste image, the file will be rename, but the name in .md is still the original one.

**Environments (please complete the following information):**
- OS: Win10
- Use markdown format ![]()
- Debug info: no "show debug info" in my command ...

**To Reproduce**
1. Ctrl+C the file or screenshot captured in picpick.
2. Paster in OB. The log will show "rename to xxx(md file title).jpg/png
3. Confirm the image file has been copy to the attachment folder and rename to xxx.jpg/png
4. But in md, the link is still pointing to the original file name before renaming.
**Screenshots**
![image](https://user-images.githubusercontent.com/104776017/170498454-cbf8c0dd-c0f0-4806-acc9-4f4833721957.png)

**Feature request
We I paste image from screenshot tool or web browser, the format is .PNG, the file size is large, is it possible to add a function to convert it to .jpg automatically? There is a plugin called"paster image png to jepg", but its rename functon is not very powerful...

Thank you for your great job!

**Comment by alx72n** [comment] 2022-06-15 07:55
Hello.
I confirm the same behavior, file is renamed, but the pasted description to the markdown file is not changed.
Obsidian: v0.14.15
OS: macOS 12.1.

**Comment by Ch4mpa9ne** [comment] 2022-06-18 12:20
I confirm the same behavior too!!!
File is renamed, but the pasted description to the markdown file is not changed!!!!!!!!!!!
Obsidian: v0.14.16
OS: macOS11.6.6

And it work some time, it not work some time, so fuck.

**Comment by aviau** [comment] 2022-06-25 05:27
Same issue here. Looks like a race condition of some sort.

**Comment by jonnymaceachern** [comment] 2022-06-26 15:57
> Looks like a race condition of some sort.

Also experiencing this. Seems to only happen sometimes, so this would make sense.

**Comment by octo-kumo** [comment] 2022-07-25 14:02
Same issue here

**Comment by HiramYang** [comment] 2022-10-11 07:50
Same issue here.

**Comment by lxq1** [comment] 2022-10-19 05:30
我也遇到了这个情况，并且提供了录屏证据

**Comment by jerviscui** [comment] 2022-10-20 02:14
These should be the same questions:

Duplicate of #24 
Duplicate of #20 
Duplicate of #13 
Duplicate of #11

**Comment by jerviscui** [comment] 2022-10-20 02:24
If disable auto rename the link is changed.

**Comment by jerviscui** [comment] 2022-10-30 03:41
Will it still be updated?

**Comment by lxq1** [comment] 2022-11-04 03:51
还继续开发更新吗？？

**Comment by reorx** [comment] 2022-11-04 10:36
To @jerviscui @lxq1 and all whom it may concern, I'm busy preparing for an exam recently and am not available to review the issues, so sorry for getting you into trouble while using this plugin. The exam ends on the 16th of November, after that I'll get back to dive into the problem ASAP.

**Comment by alexinea** [comment] 2022-12-26 05:11
It doesn't work properly in Obsidian 1.1.9 either.

**Comment by fxmarty** [comment] 2022-12-28 14:01
@reorx Any update? I love the plugin, just this not working makes things not really helpful.

**Comment by cnyyk** [comment] 2022-12-29 04:43
To Reproduce:
0. Switch off `Use [[WikiLinks]]`, 
1. Create a new note named: `Test Note`, note filename contains a space char.
2. Paste an image
   - Link text under cursor should be `![](Test%20Note.png)`
   - Dive into main.js:
     - `const originStem = file.basename;` // HERE WILL BE 'Test Node'
     - `linkTextRegex = new RegExp("!\\[\\]\\(([^[\\]]*\\/)?${originStem}\\.${ext}\\)");`
     - Obviously `Test Node` not matches `Test%20Node`

**Comment by cnyyk** [comment] 2022-12-29 04:46
To Reproduce:
1. Switch off `Use [[WikiLinks]]`, 
2. Create a new note named: `Untitled`, note filename contains a space char.
3. Paste an image
   - Link text under cursor should be `![](Pasted%20image%2020221229124433.png)`
   - Dive into main.js:
     - `const originStem = file.basename;` // HERE WILL BE 'Test Node'
     - `linkTextRegex = new RegExp("!\\[\\]\\(([^[\\]]*\\/)?${originStem}\\.${ext}\\)");`
     - Obviously `Pasted image 20221229124433.png` not matches `Pasted%20image%2020221229124433.png`

**Comment by cnyyk** [comment] 2022-12-29 04:48
To Reproduce:
1. Switch off `Use [[WikiLinks]]`, 
2. Create a new note named: `Untitled`, note filename contains a space char.
3. Paste an image
   - Link text under cursor should be `![](Pasted%20image%2020221229124433.png)`
   - Dive into main.js:
     - `const originStem = file.basename; // HERE WILL BE 'Pasted image 20221229124433.png'`
     - `linkTextRegex = new RegExp("!\\[\\]\\(([^[\\]]*\\/)?${originStem}\\.${ext}\\)");`
     - `Pasted image 20221229124433.png` not matches `Pasted%20image%2020221229124433.png`

**Comment by one0oneChen** [comment] 2023-01-05 15:53
测试了一下只OB 1.19 只在打开WIKI语法时正常生效, 关闭WIKI语法则出现这个问题, 源码逻辑应该是有问题

**Comment by reorx** [comment] 2023-01-28 14:37
Hey guys, this issue should be fixed in [1.6.0](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.6.0), please update and try if it works. You can also look at the release log, which contains more details and my sincere gratitude to you.

**Closed by reorx** 2023-01-28 14:37 UTC
Labels: bug
